image: node:latest

stages:
  - lint
  - test

before_script:
  - NODE_ENV=test npm i

after_script:
  - npm run reset

linting:
  stage: lint
  script:
    - npm run lint

testing:
  stage: test
  script:
    - npm test
