image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - lint
  - test

before_script:
  - sudo apt update
  - sudo apt install --no-install-recommends -y \
      software-properties-common ca-certificates build-essential make curl wget
  - NODE_ENV=test npm i

after_script:
  - npm run reset

linting:
  stage: lint
  script:
    - npm run lint

testing:
  stage: test
  script:
    - npm test
