os:
  - linux
sudo: false
language: node_js
node_js:
  - "7.10"
  - "7.6"
  - "7.0"
  - "6.9.2"
  - "6.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i
after_success:
  - npm run coveralls
